---
services:
  ansible:
    image: python:3.12-slim
    container_name: ansible
    volumes:
      - /compose/playbooks:/ansible/playbooks
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Calgary
    command: /bin/bash -c "pip install ansible && tail -f /dev/null"
    restart: unless-stopped
