---
services:
  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
      # - 9000:9000 # Optional: Open port 9000 for HTTP access
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /compose/portainer/portainer_data:/data
    #healthcheck:
      #test: ["CMD-SHELL", "curl --fail http://IP_ADDRESS:9000 || exit 0"]
      #interval: 40s
      #timeout: 10s
      #retries: 3
    restart: unless-stopped
