global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: ERROR
  format: common
  filePath: /compose/traefik/logs/traefik.log

accesslog:
  format: common
  filePath: /compose/traefik/logs/access.log

api:
  dashboard: true
  insecure: true

entryPoints:
  midgard:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: asgard
          scheme: https
  asgard:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /compose/traefik
    watch: true

certificatesResolvers:
  staging:
    acme:
      email: alprojects1@proton.me
      storage: /compose/traefik/certs/acme-staging.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: midgard

  production:
    acme:
      email: alprojects1@proton.me
      storage: /compose/traefik/certs/acme-production.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: midgard

# Optional: Disable TLS cert verification
serversTransport:
  insecureSkipVerify: true

# Optional: Overwrite Default Certificates
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /compose/traefik/certs/cert.pem
        keyFile: /compose/traefik/certs/cert-key.pem
  options:
    default:
      minVersion: VersionTLS12
