---
services:
  traefik:
    image: docker.io/library/traefik:v3.1.2
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # Enable Dashboard, Protect in production
    volumes:
      - /compose/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /compose/traefik/conf/:/etc/traefik/conf/
      - /compose/traefik/certs/:/etc/traefik/certs/
      - /run/docker.sock:/run/docker.sock
    environment:
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://10.100.100.234:8686 || exit 0"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped
