
    services:
  tracker:
    image: lscr.io/linuxserver/speedtest-tracker:0.21.2
    container_name: speedtest-tracker
    ports:
      - 8686:80
      - 8443:443
    volumes:
      - /compose/tracker/config:/config
      - /compose/tracker/ssl-keys:/config/keys
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=KEY
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=0 */1 * * *
      - PRUNE_RESULTS_OLDER_THAN=30
      - CHART_DATETIME_FORMAT=Y-m-d H:i
      - DATETIME_FORMAT=Y-m-d H:i:s
      - APP_TIMEZONE=America/New_York
      - APP_NAME=MySpeedTracker
      - APP_URL=https://speedtest.net
      - DISPLAY_TIMEZONE=America/New_York
      - CONTENT_WIDTH=7xl
      - PUBLIC_DASHBOARD=false
      - DASHBOARD_POLLING=60s
      - NOTIFICATION_POLLING=60s
      - RESULTS_POLLING=false
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://IP_ADDRESS:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest.rule=Host(`speed.alprojects.org`)"
      - "traefik.http.routers.speedtest.entrypoints=asgard"
      - "traefik.http.routers.speedtest.tls.certresolver=production"
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
