services:
  traefik:
    image: docker.io/library/traefik:v3.1.2
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /compose/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /compose/traefik/certs/:/etc/traefik/certs/
      - /compose/traefik/conf/:/etc/traefik/conf/
      - /compose/traefik/acme.json:/acme.json
      - /run/docker.sock:/run/docker.sock:ro
    environment:
      - CF_API_EMAIL=EMAIL # or use secret
      - CF_DNS_API_TOKEN=KEY # or use secret
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://10.100.100.234:8686 || exit 0"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=midgard"
      - "traefik.http.routers.traefik.rule=Host(`traefik.alprojects.org`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=asgard"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.alprojects.org`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=alprojects.org"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.alprojects.org"

networks:
  traefik_default:
    external: true
