---
- Content & Media:
    - Plex:
        icon: mdi-plex #si-plex #plex.png
        href: "{{HOMEPAGE_VAR_PLEX_HREF}}"
        description: Media Transcoder
        ping: "{{HOMEPAGE_VAR_PLEX_PING}}"
        widget:
          type: plex
          url: "{{HOMEPAGE_VAR_PLEX_URL}}"
          key: "{{HOMEPAGE_VAR_PLEX_API_KEY}}"

    - Sonarr:
        icon: si-sonarr #sonarr.png
        href: "{{HOMEPAGE_VAR_SONARR_HREF}}"
        description: Series Organization
        ping: "{{HOMEPAGE_VAR_SONARR_PING}}"
        widget:
          type: sonarr
          url: "{{HOMEPAGE_VAR_SONARR_URL}}"
          key:

    - Radarr:
        icon: si-radarr #mdi-radar #radarr.png
        href: "{{HOMEPAGE_VAR_RADARR_HREF}}"
        description: Movie Organization
        ping: "{{HOMEPAGE_VAR_RADARR_PING}}"
        widget:
          type: radarr
          url: "{{HOMEPAGE_VAR_RADARR_URL}}"
          key:

    - qBittorrent:
        icon: si-qbittorrent #mdi-download #qbittorrent.png
        href: "{{HOMEPAGE_VAR_QBITTORRENT_HREF}}"
        description: Peer2Peer Client
        ping: "{{HOMEPAGE_VAR_QBITTORRENT_PING}}"
        widget:
          type: qbittorrent
          url: "{{HOMEPAGE_VAR_QBITTORRENT_URL}}"
          username: "{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}"
          password: "{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}"

- Infrastructure & Data:
    - Proxmox:
        icon: si-proxmox #mdi-server #proxmox.png  
        href: "{{HOMEPAGE_VAR_PROXMOX_HREF}}"
        description: Hypervisor 1
        ping: "{{HOMEPAGE_VAR_PROXMOX_PING}}"
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
          node: pve

    - Proxmox2:
        icon: si-proxmox #mdi-server #proxmox.png
        href: "{{HOMEPAGE_VAR_PROXMOX_HREF_2}}"
        description: Hypervisor 2
        ping: "{{HOMEPAGE_VAR_PROXMOX_PING_2}}"
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL_2}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY2}}"
          node: pve2

    - TrueNAS:
        icon: si-truenas
        href: 
        description: Network Attached Storage
        ping: 
        widget:
          type: truenas
          url: 
          username: 
          password: 
          key: 
          enablePools: true 
          nasType: scale #
    - QNAP:
        icon: mdi-nas #si-qnap #qnap.png
        href: "{{HOMEPAGE_VAR_QNAP_HREF}}"
        description: Storage Network Area
        ping: "{{HOMEPAGE_VAR_QNAP_PING}}"
        widget:
          type: qnap
          url: "{{HOMEPAGE_VAR_QNAP_URL}}"
          username: Gizmo"{{HOMEPAGE_VAR_QNAP_USER}}"
          password: Tensai!@#123 "{{HOMEPAGE_VAR_QNAP_PWD}}"

- Service & Host:
    - Pi-hole:
        icon: si-pi-hole #mdi-pi-hole #pi-hole.png
        href: "{{HOMEPAGE_VAR_PIHOLE_HREF}}"
        description: Recursive Domain
        ping: "{{HOMEPAGE_VAR_PIHOLE_PING}}"
        widget:
          type: pihole
          url: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"

    - Pi-hole2:
        icon: si-pi-hole #mdi-pi-hole #pi-hole.png
        href: "{{HOMEPAGE_VAR_PIHOLE_HREF_2}}"
        description: Forwarding Domain
        ping: "{{HOMEPAGE_VAR_PIHOLE_PING_2}}"
        widget:
          type: pihole
          url: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}"
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_2}}"

    - Cloudflare:
        icon: si-cloudflare #mdi-cloud #cloudflare.png
        href: "{{HOMEPAGE_VAR_CLOUDFLARE_HREF}}"
        description: Mx Tunnel
        ping: "{{HOMEPAGE_VAR_CLOUDFLARE_PING}}"
        widget:
          type: cloudflared
          url: "{{HOMEPAGE_VAR_CLOUDFLARE_URL}}"
          accountid: "{{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID}}"
          tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID}}"
          key: "{{HOMEPAGE_VAR_CLOUDFLARE_API_KEY}}"

    - Cloudflare2:
        icon: si-cloudflare #mdi-cloud #cloudflare.png
        href: "{{HOMEPAGE_VAR_CLOUDFLARE_HREF}}"
        description: Px Tunnel
        ping: "{{HOMEPAGE_VAR_CLOUDFLARE_PING}}"
        widget:
          type: cloudflared
          url: "{{HOMEPAGE_VAR_CLOUDFLARE_URL}}"
          accountid: "{{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID}}"
          tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID_2}}"
          key: "{{HOMEPAGE_VAR_CLOUDFLARE_API_KEY}}"

- Identity & security:
    - Authentik:
        href: "{{HOMEPAGE_VAR_AUTHENTIK_HREF}}"
        description: Access Organization
        ping: "{{HOMEPAGE_VAR_AUTHENTIK_PING}}"
        icon: si-authentik #authentik.png
        widget:
            type: authentik
            url: "{{HOMEPAGE_VAR_AUTHENTIK_URL}}"
            key: "{{HOMEPAGE_VAR_AUTHENTIK_API_KEY}}"

    - Bitwarden:
        href: "{{HOMEPAGE_VAR_HOME_PASSBOLT_HREF}}"
        description: Password Organization
        icon: si-bitwarden #passbolt.png

    - Twingate:
        href: "{{HOMEPAGE_VAR_TWINGATE_HREF}}"
        description: Zero Trust
        icon: si-openlayers #mdi-key #twingate.png

    - Traefik:
        icon: si-traefikproxy #mdi-traffic-light #traefik.png
        href: "{{HOMEPAGE_VAR_TRAEFIK_HREF}}"
        description: Proxy Management
        ping: "{{HOMEPAGE_VAR_TRAEFIK_PING}}"
        widget:
          type: traefik
          url: "{{HOMEPAGE_VAR_TRAEFIK_URL}}"
          username: "{{HOMEPAGE_VAR_TRAEFIK_USERNAME}}" # Optional if authentication is needed
          password: "{{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}" # Optional if authentication is needed


- Automation & Iot:
    - Speed Tracker:
        icon: si-speedtest #mdi-speedometer
        href: "{{HOMEPAGE_VAR_TRACKER_HREF}}"
        description: Speed Tracking
        ping: "{{HOMEPAGE_VAR_TRACKER_PING}}"
        container: speedtest
#        widget:
#            type: speedtest
#            url: "{{HOMEPAGE_VAR_TRACKER_URL}}"
    - Kestra:
        href: "{{HOMEPAGE_VAR_KESTRA_HREF}}"
        description: Logcal Path Automation
        ping: "{{HOMEPAGE_VAR_KESTRA_PING}}"
        icon: si-testrail ##https://kestra-io.gallerycdn.vsassets.io/extensions/kestra-io/kestra/0.0.1/1692285562923/Microsoft.VisualStudio.Services.Icons.Default

    - Ansible Semaphore:
        href: "{{HOMEPAGE_VAR_ANSIBLE_HREF}}"
        description: Lxc & Vm Automation
        ping: "{{HOMEPAGE_VAR_ANSIBLE_PING}}"
        icon: si-ansible #si-ansible-#EE0000

    - Cyber Power:
        href: "{{HOMEPAGE_VAR_CYBER_POWER_HREF}}"
        description: Power Orginization
        ping: "{{HOMEPAGE_VAR_CYBER_POWER_PING}}"
        icon: mdi-power-plug-battery

    - Brother MFP:
        href: "{{HOMEPAGE_VAR_BROTHER_PRINTER_HREF}}"
        description: Printer
        ping: "{{HOMEPAGE_VAR_BROTHER_PRINTER_PING}}"
        icon: mdi-printer

    - OpenPrinting CUPS:
        href: "{{HOMEPAGE_VAR_CUPS_HREF}}"
        description: Printer Orginization
        ping: "{{HOMEPAGE_VAR_CUPS_PING}}"
        icon: mdi-coffee

#   - Home Assistant:
 #       icon: si-homeassistant
 #       href: "{{HOMEPAGE_VAR_HOME_ASSISTANT_HREF}}"
 #       description: Home Automation
 #       ping: "{{HOMEPAGE_VAR_HOME_ASSISTANT_PING}}"
 #       container: homeassistant
 #       widget:
 #         type: homeassistant
 #         url: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
 #         key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}}"

