---
services:
  gitlab:
    image: gitlab/gitlab-ce:17.3.1-ce.0
    container_name: gitlab
    hostname: "gitlab.alprojects.tech"
    ports:
      - "3200:22"
      # - "8929:8929" Managed by Traefik
      # - "4435:443" Managed by Traefik
    volumes:
      - /compose/gitlab/config:/etc/gitlab
      - /compose/gitlab/logs:/var/log/gitlab
      - /compose/gitlab/data:/var/opt/gitlab
    shm_size: "256m"
    networks:
      - frontend
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://IP_ADDRESS || exit 1"]
      interval: 40s
      timeout: 10s
      retries: 3
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab-https.rule=Host("gitlabs.alprojects.org")
      - traefik.http.routers.gitlab-https.entrypoints=asgard
      - traefik.http.routers.gitlab-https.tls=true
      - traefik.http.routers.gitlab-https.tls.certresolver=cloudflare
      - traefik.http.services.gitlab-service.loadbalancer.server.port=80
    restart: unless-stopped
    
networks:
  traefik_default:
    asgard: true
