# Collection of handy function to use 

---
- name: Custom functions on all hosts
  hosts: all
  become: true 
  tasks:
    - name: Add function block to .bashrc
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        block: |
          # Custom Functions

          # IT function collection:
          huntit() {
              sudo find / -name "$1*" 2>/dev/null
          }

          killit() {
              pkill -f "$1"
          }

          backit() {
              src="$1"
              dest="$2"
              filename=$(basename "$src")

              if [ -z "$src" ] || [ -z "$dest" ]; then
                  echo "Usage: backit /path/to/source /path/to/backup/destination"
                  return 1
              fi

              tar -czvf "$dest/$filename-$(date +%Y%m%d%H%M%S).tar.gz" "$src"
          }

          sendit() {
              src="$1"
              dest="$2"

              if [ -z "$src" ] || [ -z "$dest" ]; then
                  echo "Usage: sendit /path/to/source user@remote:/path/to/destination"
                  return 1
              fi

              rsync -avh --progress "$src" "$dest"
          }

          # Compose function collection
          function compose_ip() {
              container=$1
              docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container
          }

          function compose_shell() {
              container=$1
              shell_command=${2:-/bin/sh}  # Default to /bin/sh if no second argument is provided
              docker exec -it $(docker ps -qf "name=$container") $shell_command
          }

          function compose_inspect() {
              container=$1
              docker inspect $(docker ps -qf "name=$container")
          }

          # Ansible function collection
          function ansible_update() {
              ansible-playbook -i /ansible/venv/inventory /ansible/venv/playbooks/update-hosts.yaml
          }

          function ansible_kali() {
              ansible-playbook -i /ansible/venv/inventory /ansible/venv/playbooks/ansible-kali.yaml
          }

          function ansible_sshd() {
              ansible-playbook -i /ansible/venv/inventory /ansible/venv/playbooks/ansible-sshd.yaml
          }

    - name: Reload bash to apply functions
      ansible.builtin.shell: "source {{ ansible_env.HOME }}/.bashrc"
      args:
        executable: /bin/bash
