---
- name: Configure SSHD on all hosts
  hosts: all
  become: true  # Ensure we are using root for this operation
  tasks:
    - name: Ensure SSH is listening on the correct port
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Port'
        line: 'Port {{ ansible_port | default(22) }}'
        state: present

    - name: Allow root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present

    - name: Enable public key authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present

    - name: Disable password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    - name: Disable empty passwords
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitEmptyPasswords'
        line: 'PermitEmptyPasswords no'
        state: present

    - name: Set MaxAuthTries to 1
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxAuthTries'
        line: 'MaxAuthTries 1'
        state: present

    - name: Set MaxSessions to 1
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxSessions'
        line: 'MaxSessions 1'
        state: present

    - name: Set LoginGraceTime to 1m
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^LoginGraceTime'
        line: 'LoginGraceTime 1m'
        state: present

    - name: Set AddressFamily to inet (IPv4 only)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AddressFamily'
        line: 'AddressFamily inet'
        state: present

    - name: Set UsePAM to yes
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^UsePAM'
        line: 'UsePAM yes'
        state: present

    - name: Restart SSH service to apply changes
      ansible.builtin.service:
        name: sshd
        state: restarted
