---
services:
  gitlab:
    image: gitlab/gitlab-ce:17.5.5-ce.0
    container_name: gitlab
    ports:
      - "3200:22"
      - "8929:8929" #Managed by Traefik
      - "4435:443"  #Managed by Traefik
    volumes:
      - /compose/gitlab/config:/etc/gitlab
      - /compose/gitlab/logs:/var/log/gitlab
      - /compose/gitlab/data:/var/opt/gitlab
    shm_size: "256m"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://IP_ADDRESS || exit 0"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    #labels:
     # - "traefik.enable=true"
     # - "traefik.http.routers.gitlab-https.rule=Host('gitlab.alprojects.org')"
     # - "traefik.http.routers.gitlab-https.entrypoints=asgard"
     # - "traefik.http.routers.gitlab-https.tls.certresolver=production"
     # - "traefik.http.services.gitlab-service.loadbalancer.server.port=80"
    #networks:
     # - traefik_default

#networks:
  #traefik_default:
    #external: true
