---
services:
  gitlab:
    image: gitlab/gitlab-ce:17.3.1-ce.0
    container_name: gitlab
    hostname: "gitlab.alprojects.tech"
    ports:
      - "3200:22"
      - "8929:8929" 
      - "4435:443" 
    volumes:
      - /compose/gitlab/config:/etc/gitlab
      - /compose/gitlab/logs:/var/log/gitlab
      - /compose/gitlab/data:/var/opt/gitlab
    shm_size: "256m"
    networks:
      - frontend
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://IP_ADDRESS || exit 1"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    
