---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    env_file:
      - .env
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /compose/homepage:/app/config
      - /compose/homepage:/app/public/images
      - /compose/homepage:/app/public/icons
      #- /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: $PUID
      PGID: $PGID
    restart: unless-stopped
