---
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    ports:
      - 9117:9117
    volumes:
      - /compose/jackett/data:/config
      - /compose/jackett/blackhole:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Toronto
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://IP_ADDRESS:8989 || exit 0"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped
