---
services:
  kali:
    image: lscr.io/linuxserver/kali-linux:latest
    container_name: kali-linux
    security_opt:
      - seccomp:unconfined # allowing all system calls in the container/this is needed for older apps 
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Calgary
      - SUBFOLDER=/kali
      - "TITLE=Gizmo Linux"
    volumes:
      - /compose/kali/data:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri # Containers that need direct access to the GPU for hardware-accelerated 
    shm_size: "1gb" # Anything lower breaks modren browsers
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://IP_ADDRESS:3001 || exit 0"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped
