---
services:
  kali-linux:
    image: lscr.io/linuxserver/kali-linux:latest
    container_name: kali-linux
    hostname: KALI01
    ports:
      - 3004:3004
      - 3002:3001
      - 5901:5901
    volumes:
      - /compose/kali/data:/config
      - /compose/kali/home:/home/echo
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /compose/kali/etc/hosts:/etc/hosts
      - /compose/kali/var/lib/apt:/var/lib/apt
      - /compose/kali/var/lib/dpkg:/var/lib/dpkg
      - /compose/kali/var/cache/apt:/var/cache/apt
      - /compose/kali/etc/hostname:/etc/hostname
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /compose/kali/etc/resolv.conf:/etc/resolv.conf
      - /compose/kali/data/ssl/cert.pem:/etc/nginx/cert.pem
      - /compose/kali/data/ssl/cert.key:/etc/nginx/cert.key
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    security_opt:
      - seccomp=unconfined
      - no-new-privileges=false
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Calgary
      #- SUBFOLDER=/kali
      - TITLE="Gizmo_Linux"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3001 || exit 0"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped
