---
services:
  kali:
    image: lscr.io/linuxserver/kali-linux:latest
    container_name: kali-linux
    security_opt:
      - seccomp:unconfined # allowing all system calls in the container/this is needed in my case 
      - no-new-privileges:false
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Calgary
      #- SUBFOLDER=/kali
      - TITLE="Gizmo Linux"
    volumes:
      - /compose/kali/data:/config
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3004:3004
      - 3002:3001
    devices:
      - /dev/dri:/dev/dri # for containers that need direct access to the GPU
    shm_size: "1gb" # Anything lower breaks modren browsers
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://IP_ADDRESS:3001 || exit 0"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped
