---
services:
  metasploitable2:
    image: tleemcjr/metasploitable2
    container_name: metas2
    ports:
      - 8888:8888
      - 8787:80
      - 4422:22
    volumes:
      - /compose/metas/data:/data
      - /compose/metas/certs:/usr/local/share/ca-certificates
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Calgary
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://IP_ADDRESS:80 || exit 0"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - kali_default

networks:
  kali_default:
    external: true
