services:
  metasploit:
    build: .
    container_name: metas2-debian
    ports:
      - 5432:5432
    volumes:
      - /compose/metas-debian/data:/data
      - /compose/metas-debian/config:/opt/metasploit-framework/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Calgary
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:5432 || exit 0"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - kali_default

networks:
  kali_default:
    external: true
