---
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    security_opt:
      - seccomp:unconfined
    ports:
      - "33000:3000"
      - "33001:3001"
    volumes:
      - /compose/obsidian/config:/config
      - /compose/obsidian/dir:/dir
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Calgary
      - CUSTOM_PORT=3000
      - CUSTOM_HTTPS_PORT=3001
      - CUSTOM_USER=USER_NAME_HERE
      - PASSWORD=PASSWORD_HERE
      - TITLE="Gizmo's Obsidian Secure Notes"
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://IP_ADDRESS:33000 || exit 0"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped
