---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:5.9.1.9070-ls234
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - /compose/radarr/data:/config
      - /mnt/iscsi/Movies:/movies
      - /mnt/iscsi:/mnt/iscsi
      - /mnt/iscsi/Anime-Movies:/anime-movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://IP_ADDRESS:7878 || exit 0"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped
