---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.12.2823-ls267
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - /compose/sonarr/data:/config
      - /mnt/iscsi/Shows:/shows
      - /mnt/iscsi:/mnt/iscsi
      - /mnt/iscsi/Anime-Shows:/anime-shows
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://**************:8989 || exit 0"]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stoppe
