---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.8.1874-ls250
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/iscsi/sonarr/data:/config
      - /mnt/iscsi/Shows:/tv
      - /mnt/iscsi/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
