---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.8.1874-ls250
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /compose/sonarr:/config
      - /mnt/iscsi/Shows:/shows
    ports:
      - 8989:8989
    healthcheck:
      test: ["CMD", "curl", "-f", "http://IP_ADDRESS_HERE:8989 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

